name = "erc8004-web"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages build output directory - for manual wrangler deploys
# For Cloudflare Dashboard with Next.js preset, use .next
pages_build_output_dir = ".next"

# Cloudflare Pages configuration
# Note: Environment variables should be configured in Cloudflare Pages dashboard
# Settings → Environment variables

# For local development with wrangler
# [env.development]
# vars = { NODE_ENV = "development" }

# For production
# [env.production]
# vars = { NODE_ENV = "production" }
